/*SCHEMA DO PROJETO: Aula04

REMOVER DATABASE*/
DROP DATABASE Aula04;

/*CRIAR A BASE NOVAMENTE*/
CREATE DATABASE Aula04;

/*SELECIONAR O BANCO Aula04 (NAMESPACE Aula04)*/

USE Aula04;

/*CRIACAO DA TABELA USUARIO*/
CREATE TABLE usuarios (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL

);

/*CRIACAO DA TABELA PARA REGISTRAR OS LOGINS DO USUARIO*/
CREATE TABLE logs (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	USUARIO_ID INT,
	LOGIN_DATA TIMESTAMP,
	ACAO VARCHAR(100) NOT NULL,

	FOREIGN KEY (USUARIO_ID) REFERENCES usuarios(ID)

);


